# Generated by Django 5.2.1 on 2025-05-19 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Área de Programação',
                'verbose_name_plural': 'Áreas de Programação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.area')),
                ('tecnologias', models.ManyToManyField(to='enquete.tecnologia')),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('unica', 'Única Escolha'), ('multipla', 'Múltipla Escolha')], max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.enquete')),
                ('tecnologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquete.tecnologia')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('peso', models.IntegerField(default=1)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.pergunta')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=50)),
                ('tecnologias_interesse', models.ManyToManyField(blank=True, to='enquete.tecnologia')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MultiplaEscolhaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.aluno')),
                ('opcoes', models.ManyToManyField(to='enquete.opcao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.pergunta')),
            ],
            options={
                'verbose_name': 'Resposta Múltipla Escolha',
                'verbose_name_plural': 'Respostas Múltiplas Escolhas',
                'ordering': ['-data_resposta'],
                'unique_together': {('aluno', 'pergunta')},
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.aluno')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.opcao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['-data_resposta'],
                'unique_together': {('aluno', 'pergunta')},
            },
        ),
    ]
