# Generated by Django 5.2.1 on 2025-05-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, to='enquete.tecnologia'),
        ),
    ]
