# Generated by Django 5.2.1 on 2025-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0004_alter_multiplaescolharesposta_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
