# Generated by Django 5.2.1 on 2025-05-27 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0005_enquete_data_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='enquete.enquete'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('UNICA_ESCOLHA', 'Única Escolha'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha')], max_length=20),
        ),
    ]
